In [ ]:
import tensorflow as tf
import numpy as np 
print("TF:", tf.__version__)
#check

TF: 2.16.2


# Scalars, vectors, matrices

In [64]:

scalar = tf.constant(7)
vector = tf.constant([10, 20, 30])
matrix = tf.constant([[1., 2.], [3., 4.]])
tensor  = tf.constant([[[1],[2]], [[3],[4]]])

print("Scalar shape:", scalar.shape)
print("Vector shape:", vector.shape)
print("Matrix shape:", matrix.shape)
print("Tensor shape:", tensor.shape)


Scalar shape: ()
Vector shape: (3,)
Matrix shape: (2, 2)
Tensor shape: (2, 2, 1)


 Data types and Casting

In [65]:
x = tf.constant([1.7, 7.4])
y = tf.constant([7, 10])

x16 = tf.cast(x, tf.float16)
y32 = tf.cast(y, tf.float32)

print(x16)
print(y32)


tf.Tensor([1.7 7.4], shape=(2,), dtype=float16)
tf.Tensor([ 7. 10.], shape=(2,), dtype=float32)


Indexing and shaping

In [66]:
rank2 = tf.constant([[10, 7],[3, 4]])

last_col = rank2[:, -1]        # column slice
expanded = tf.expand_dims(rank2, -1)  # add channel-like axis
squeezed = tf.squeeze(expanded, axis=-1)

print("Last column:", last_col)
print("Expanded shape:", expanded.shape)
print("Squeezed shape:", squeezed.shape)

Last column: tf.Tensor([7 4], shape=(2,), dtype=int32)
Expanded shape: (2, 2, 1)
Squeezed shape: (2, 2)


4) Broadcasting & basic ops


In [67]:
A = tf.constant([[10., 7.], [3., 4.]]) 
print("A+10:\n", A + 10) 
print("A*2:\n", A * 2)

A+10:
 tf.Tensor(
[[20. 17.]
 [13. 14.]], shape=(2, 2), dtype=float32)
A*2:
 tf.Tensor(
[[20. 14.]
 [ 6.  8.]], shape=(2, 2), dtype=float32)


 Matrix multiplication rules (inner dims match)

In [68]:
X = tf.constant([[1, 2], [3, 4], [5, 6]], dtype=tf.float32) # (3x2)
Y = tf.constant([[7, 8], [9, 10], [11, 12]], dtype=tf.float32) # (3x2) 
XtY = tf.matmul(X, tf.transpose(Y)) # (3x2) @ (2x3) -> (3x3)
print(XtY)

tf.Tensor(
[[ 23.  29.  35.]
 [ 53.  67.  81.]
 [ 83. 105. 127.]], shape=(3, 3), dtype=float32)


Aggregations

In [69]:
E = tf.constant(np.random.randint(0, 100, size=10)) 
print("min:", tf.reduce_min(E).numpy(),
"max:", tf.reduce_max(E).numpy(),
"mean:", tf.reduce_mean(tf.cast(E, tf.float32)).numpy(), "sum:", tf.reduce_sum(E).numpy())

min: 19 max: 95 mean: 56.0 sum: 560


One-hot encoding

In [70]:
idx = tf.constant([0, 1, 2, 3])
oh = tf.one_hot(idx, depth=4)
print(oh)


tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)


 NumPy interop

In [71]:
arr = np.array([3., 7., 10.])
t =tf.constant(arr)#NumPy->Tensor 
back_to_np = t.numpy() # Tensor -> NumPy
print("Original array:", arr)
print("Tensor:", t)
print("Back to NumPy:", back_to_np)

Original array: [ 3.  7. 10.]
Tensor: tf.Tensor([ 3.  7. 10.], shape=(3,), dtype=float64)
Back to NumPy: [ 3.  7. 10.]
